import type { ProjectItemType } from "@/types";

export const PROJECTS: ProjectItemType[] = [
  {
    id: 1,
    title: "Sign Language (Kotlin)",
    date: "October 2025 - Present",
    description: "Learn Mongolian sign language with interactive lessons.",
    imageUrl: "/images/app-placeholder.jpg",
    imageAlt: "Sign Language Dictionary",
    github: "https://github.com/hiretimsf",
    liveDemo: "https://github.com/hiretimsf",
    skills: [
      "Android Development",
      "Jetpack Compose",
      "Navigation 3",
      "DataStore",
      "Kotlin Coroutines",
      "Kotlin Flow",
      "Ktor",
      "Retrofit",
      "OkHttp",
      "Dagger Hilt",
      "Hilt",
      "Room DB",
      "Material Design 3",
    ],
    category: "Android",
  },
  {
    id: 2,
    title: "Portfolio Website v3",
    date: "October 2025 - Present",
    description:
      "Built with Next.js 16 and TailwindCSS. Designed and developed from the ground up, inspired by my own headshot. Features a modern, clean, and responsive design, with a focus on performance and SEO optimization.",
    imageUrl: "/images/apps/web/portfolio-app-v3.jpg",
    imageAlt: "Portfolio Website",
    github: "https://github.com/hiretimsf/Portfolio-Web-v3",
    liveDemo: "https://hiretimsf.com",
    skills: ["Next.js", "TypeScript", "Tailwind CSS", "Shadcn UI"],
    category: "Web",
  },
  {
    id: 3,
    title: "Portfolio Website v2",
    date: "January 2025 - March 2025",
    description:
      "Built with Next.js 15 and TailwindCSS. A modern, fast, fully responsive portfolio website with SEO optimization, MDX blog system, and custom react motion animations.",
    imageUrl: "/images/apps/web/portfolio-app-v2.jpg",
    imageAlt: "Portfolio Website",
    github: "https://github.com/timtbdev/Next.js-Portfolio-App",
    liveDemo: "https://tim-portfolio-web-v2.vercel.app/",
    skills: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Shadcn Ui",
      "TanStack Query",
      "FumaDocs",
      "Content Collection",
      "MDX",
      "Nuqs",
      "Framer Motion",
      "Resend",
    ],
    category: "Web",
  },
  {
    id: 4,
    title: "Full-Stack Blog App",
    date: "June 2023 - October 2023",
    description:
      "A fully responsive full-stack blog app built with Next.js 13, TypeScript, TailwindCSS, and Supabase as backend. Based on Shadcn UI components.",
    imageUrl: "/images/apps/web/blog-app.jpg",
    imageAlt: "Blog App",
    github: "https://github.com/timtbdev/Next.js-Blog-App",
    liveDemo: "https://ubdotcafe.vercel.app",
    skills: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Shadcn UI",
      "Supabase",
      "Drizzle",
      "Zustand",
      "FumaDocs",
      "Nuqs",
      "MDX",
      "SEO",
      "Responsive Design",
      "Accessibility",
      "Framer Motion",
    ],
    category: "Web",
  },
  {
    id: 5,
    title: "Portfolio Website v1",
    date: "January 2023 - June 2023",
    description:
      "Built with Next.js 13 and TailwindCSS. This is the first version of my portfolio website.",
    imageUrl: "/images/apps/web/portfolio-app-v1.jpg",
    imageAlt: "Portfolio Website",
    github: "https://github.com/hiretimsf/Portfolio-Web-v1",
    liveDemo: "https://tim-portfolio-web-v1.vercel.app/",
    skills: ["Next.js", "TypeScript", "Tailwind CSS", "Shadcn UI"],
    category: "Web",
  },
  {
    id: 6,
    title: "Portfolio App (Kotlin)",
    date: "April 2017 - July 2020",
    imageUrl: "/images/apps/android/portfolio-app-kotlin.jpg",
    imageAlt: "Portfolio App (Kotlin)",
    description:
      "A Kotlin-based portfolio app using Jetpack Components, MVVM, Room, and Coroutines for seamless offline/online syncing.",
    liveDemo: "https://www.youtube.com/watch?v=YjVJyqcv5I8",
    github: "https://github.com/timtbdev/Android-Portfolio-App-Kotlin",
    skills: [
      "Kotlin",
      "MVVM",
      "Jetpack Components",
      "Material Design 2",
      "Navigation",
      "Room DB",
      "Retrofit",
      "OkHttp",
      "Koin",
      "ViewModel",
      "LiveData",
      "DataBinding",
      "Leak Canary",
      "Unit Testing",
      "Shape Shifter",
      "SVG Animation",
      "Firebase",
      "Dark Theme",
    ],
    category: "Android",
  },
  {
    id: 7,
    title: "Portfolio App (Java)",
    date: "April 2017 - July 2020",
    imageUrl: "/images/apps/android/portfolio-app-java.jpg",
    imageAlt: "Portfolio App (Java)",
    description:
      "A Java-based Android portfolio app showcasing my development skills, built with standard SDK APIs and MVC architecture.",
    liveDemo: "https://www.youtube.com/watch?v=j56fSGqF7Ho",
    github: "https://github.com/timtbdev/Android-Portfolio-App-Java",
    skills: ["Java", "XML", "MVC", "Material Design 2", "Retrofit", "OkHttp"],
    category: "Android",
  },
  {
    id: 8,
    title: "Portfolio Website v0",
    date: "April 2017 - June 2020",
    description:
      "This is the first version of my portfolio site, built with HTML, CSS, and jQuery.",
    imageUrl: "/images/apps/web/portfolio-app-v0.jpg",
    imageAlt: "Portfolio Website v0",
    liveDemo: "https://personal-website-76368.web.app/index.html",
    skills: ["HTML", "CSS", "JavaScript", "Firebase"],
    category: "Web",
  },
  {
    id: 9,
    title: "Renewable Energy Project",
    date: "September 2012 - November 2013",
    description:
      "Designed and developed from the ground up with HTML, CSS, and JavaScript to highlight the key advantages of a renewable energy initiative.",
    imageUrl: "/images/apps/web/renewable-energy-app.jpg",
    imageAlt: "Renewable Energy Project",
    liveDemo: "https://ioco-5c746.web.app/eg/index.html",
    skills: ["HTML", "Cascading Style Sheets (CSS)", "JavaScript", "jQuery"],
    category: "Web",
  },
  {
    id: 10,
    title: "Project Marketing Materials",
    date: "September 2012 - November 2013",
    description:
      "Marketing materials and visuals were created in Photoshop, along with videos in After Effects. A lot of effort went into highlighting the project's benefits and making the content engaging.",
    imageUrl: "/images/apps/web/renewable-energy-marketing-materials.jpg",
    imageAlt: "Renewable Energy Marketing Materials",
    liveDemo:
      "https://drive.google.com/file/d/1TJTkNLywZL3Z_MaKLHGfsu5q_NJ-Bjo_/view?usp=sharing",
    skills: ["Adobe Photoshop", "Adobe Illustrator"],
    category: "Web",
  },
  {
    id: 11,
    title: "T-shirt Design App",
    date: "September 2012 - November 2013",
    imageUrl: "/images/apps/android/tshirt-app.jpg",
    imageAlt: "T-shirt Design App",
    description:
      "Developed a custom T-shirt design app featuring exclusive collections by renowned Mongolian designer @ido.dsnr, blending modern aesthetics with cultural inspiration.",
    liveDemo: "https://www.youtube.com/watch?v=my5CPizUXEg",
    skills: ["Java", "XML", "Android SDK", "Eclipse IDE", "Android SDK Plugin"],
    category: "Android",
  },
  {
    id: 12,
    title: "Local Marketplace App",
    date: "September 2012 - November 2013",
    imageUrl: "/images/apps/android/local-market-place-app.jpg",
    imageAlt: "Local Marketplace App",
    description:
      "A local marketplace app for buying and selling items in your neighborhood.",
    liveDemo: "https://www.youtube.com/watch?v=2TeqDGT7ATk",
    skills: ["Java", "XML", "Android SDK", "Eclipse IDE", "Android SDK Plugin"],
    category: "Android",
  },
  {
    id: 13,
    title: "Product Landing Page",
    date: "November 2009 - August 2012",
    description:
      "A product landing page built with HTML and CSS that boosted user engagement by 10%.",
    imageUrl: "/images/apps/web/product-landing-page-blackberry.jpg",
    imageAlt: "Product Landing Page",
    liveDemo:
      "https://web.archive.org/web/20100907212810/http:/www.unitel.mn/blackberry/serv.html",
    skills: ["HTML", "CSS", "JavaScript", "Photo Impact"],
    category: "Web",
  },
];
