const KEYWORDS = [
  "hire tim",
  "Tim Baz",
  "Android Developer in San Francisco Bay Area",
  "Android Developer in San Francisco",
  "Android Development",
  "Kotlin",
  "Kotlin Flows",
  "Kotlin Coroutines",
  "Java",
  "RxJava",
  "XML",
  "JSON",
  "REST",
  "Retrofit2",
  "Ktor",
  "OkHttp3",
  "Coil",
  "Glide",
  "Picasso",
  "Dagger",
  "Dagger Hilt",
  "Koin",
  "Room",
  "Datastore",
  "DataStore Preferences",
  "Firebase",
  "Jetpack Compose",
  "MVVM",
  "MVI",
  "MVC",
];

export default KEYWORDS;
